const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const SET_VISIBILITY = 'SET_VISIBILITY';
const VISIBILITY_FILTERS = {
    SHOW_ALL: 0,
    SHOW_COMPLETED: 1,
    SHOW_ACTIVE: 2
}

export {
    ADD_TODO,
    DELETE_TODO,
    TOGGLE_TODO,
    SET_VISIBILITY,
    VISIBILITY_FILTERS
}
export default {
    ADD_TODO,
    DELETE_TODO,
    TOGGLE_TODO,
    SET_VISIBILITY,
    VISIBILITY_FILTERS
}